plugins {
    id("net.fabricmc.fabric-loom") version "1.17-SNAPSHOT"
    `java-library`
}

version = "${property("mod_version")}"
group = "${property("maven_group")}"

base {
    archivesName = "MrPinoys_Pocket_Dungeons"
}

repositories {
    mavenLocal()
    maven("https://maven.nucleoid.xyz/") { name = "Nucleoid" }
}

dependencies {
    minecraft("com.mojang:minecraft:${property("minecraft_version")}")
    // No mappings: Minecraft ships unobfuscated since 26.1.
    implementation("net.fabricmc:fabric-loader:${property("loader_version")}")
    implementation("net.fabricmc.fabric-api:fabric-api:${property("fabric_api_version")}")

    // Server-side GUIs. Vanilla clients see an ordinary chest window.
    // Plain implementation rather than modImplementation: 26.x ships unobfuscated, so
    // the remapping modImplementation performs is a no-op here, and its Kotlin DSL
    // accessor is not generated by Loom in this setup.
    implementation("eu.pb4:sgui:2.1.0+26.2")
    include("eu.pb4:sgui:2.1.0+26.2")
}

// M46B: the gametest harness. Loom's own fabric-api integration creates the
// `gametest` source set, a `gameTest` run configuration that inherits `server`
// and sets the `fabric-api.gametest` system property, and the `runGameTest`
// task. Client gametests are off: this mod is server-side only and must never
// pull client classes onto a source set.
//
// The gametest source set carries its own `fabric.mod.json` (mod id
// `pocketdungeons-gametest`), so the `fabric-gametest` entrypoint is declared
// there and nothing test-related enters the shipped jar. `modId` below names
// the Loom classpath group only; it is read from that same file.
fabricApi.configureTests {
    createSourceSet = true
    modId = "pocketdungeons-gametest"
    enableGameTests = true
    enableClientGameTests = false
}

// M62: a second run configuration, alongside the "gameTest" one above,
// launching an ordinary dedicated server rather than GameTestServer. That
// difference is the whole point: GameTestServer bakes an empty LEVEL_STEM
// registry against the flat world preset and never creates a datapack
// dimension (DISCOVERIES trap 18), so it can never load the real
// pocketdungeons:void. An ordinary server run, pointed at this project's own
// bundled datapack in an isolated run directory, does load it for real.
//
// This reuses Loom's own run-configuration machinery (the same mechanism
// behind runServer and, via fabricApi.configureTests above, runGameTest)
// rather than hand-assembling a KnotServer JavaExec from scratch, since that
// machinery is Loom's supported extension point and already carries the
// classpath and JVM wiring a real launch needs. It generates a task named
// runDungeonIntegrationTest; dungeonIntegrationTest below is a thin alias so
// this milestone's task list reads the same as every other JavaExec
// verification task registered further down this file.
loom.runs {
    create("dungeonIntegrationTest") {
        server()
        name("Dungeon Integration Test")
        source(sourceSets["gametest"])
        runDir("run-dungeonIntegrationTest")
        property("pocketdungeons.integrationtest", "true")
    }
    // M76: a repeatable load test that boots the same real dedicated server
    // route as dungeonIntegrationTest (so pocketdungeons:void loads for real)
    // and drives concurrent instances through it. Two invocations: the
    // standard dungeonLoadTest (small, fast, runs in CI) and
    // dungeonLoadTestSoak (wide defaults for a long soak). Both write eula.txt
    // via the doFirst hooks below, same as dungeonIntegrationTest.
    create("dungeonLoadTest") {
        server()
        name("Dungeon Load Test")
        source(sourceSets["gametest"])
        runDir("run-dungeonLoadTest")
        property("pocketdungeons.loadtest", "true")
        // M76: optional Gradle project properties let an operator sweep the
        // envelope from the command line without editing code:
        //   -PloadtestInstances=32 -PloadtestCycles=3 -PloadtestSteadyTicks=400
        project.findProperty("loadtestInstances")?.let { property("pocketdungeons.loadtest.instances", it.toString()) }
        project.findProperty("loadtestCycles")?.let { property("pocketdungeons.loadtest.cycles", it.toString()) }
        project.findProperty("loadtestSteadyTicks")?.let { property("pocketdungeons.loadtest.steadyTicks", it.toString()) }
    }
    create("dungeonLoadTestSoak") {
        server()
        name("Dungeon Load Test Soak")
        source(sourceSets["gametest"])
        runDir("run-dungeonLoadTest")
        property("pocketdungeons.loadtest", "true")
        property("pocketdungeons.loadtest.soak", "true")
    }
}

tasks.register("dungeonIntegrationTest") {
    group = "verification"
    description = "Boots an isolated real dedicated server and proves pocketdungeons:void " +
        "loads outside the GameTestServer stand-in (LIVE_TEST_PASS 35.1)"
    dependsOn("runDungeonIntegrationTest")
}

// A real dedicated server refuses to boot the world until eula.txt agrees, and
// nothing else in this project's run directories writes that file for a fresh
// scratch directory. runGameTest doesn't hit this because the gametest
// module's own MainMixin forces Eula.hasAgreedToEULA whenever
// fabric-api.gametest is set (DISCOVERIES trap 18); this run has no such
// mixin (and isn't allowed one, per the one-mixin budget), so the file is
// written by hand before every launch instead.
tasks.named("runDungeonIntegrationTest") {
    doFirst {
        val runDir = file("run-dungeonIntegrationTest")
        runDir.mkdirs()
        file("$runDir/eula.txt").writeText("eula=true\n")
    }
}

// M76: thin aliases over the Loom-generated run tasks, so the milestone's
// task list reads the same as every other verification task. The run tasks
// themselves carry the classpath and JVM wiring; these just name them.
tasks.register("dungeonLoadTest") {
    group = "verification"
    description = "Boots a real dedicated server and drives concurrent dungeon " +
        "instances through it, reporting generation/clear/tick latency and " +
        "heap/chunk footprint. Repeatable via -Ppocketdungeons.loadtest.* properties."
    dependsOn("runDungeonLoadTest")
}

tasks.register("dungeonLoadTestSoak") {
    group = "verification"
    description = "The long-soak invocation of dungeonLoadTest: wider defaults " +
        "(more instances, cycles and steady ticks) for sustained-load evidence."
    dependsOn("runDungeonLoadTestSoak")
}

tasks.named("runDungeonLoadTest") {
    doFirst {
        val runDir = file("run-dungeonLoadTest")
        runDir.mkdirs()
        file("$runDir/eula.txt").writeText("eula=true\n")
    }
}

tasks.named("runDungeonLoadTestSoak") {
    doFirst {
        val runDir = file("run-dungeonLoadTest")
        runDir.mkdirs()
        file("$runDir/eula.txt").writeText("eula=true\n")
    }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

tasks.register<JavaExec>("doorMaskTest") {
    group = "verification"
    description = "Runs the pure-Java DoorMask regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DoorMaskTest"
}

tasks.register<JavaExec>("planSelectorTest") {
    group = "verification"
    description = "Runs the pure-Java RoomSelector/PlanRenderer regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.PlanSelectorTest"
}

tasks.register<JavaExec>("difficultyProfileTest") {
    group = "verification"
    description = "Runs the pure-Java DifficultyProfile regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DifficultyProfileTest"
}

tasks.register<JavaExec>("layoutGraphTest") {
    group = "verification"
    description = "Runs LayoutGraphGenerator's own shape/role/span verification sweep"
    // M40: the harness moved out of production source into the test source
    // set (LayoutGraphGeneratorHarness), so this points at test now, not main.
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.LayoutGraphGeneratorHarness"
}

tasks.register<JavaExec>("dungeonRoomMetaTest") {
    group = "verification"
    description = "Runs the pure-Java DungeonRoomMeta parser regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DungeonRoomMetaTest"
}

tasks.register<JavaExec>("keystoneMathTest") {
    group = "verification"
    description = "Runs the pure-Java keystone level and depletion regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.KeystoneMathTest"
}

tasks.register<JavaExec>("affixMathTest") {
    group = "verification"
    description = "Runs the pure-Java affix set, threshold, seeding and naming regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.AffixMathTest"
}

tasks.register<JavaExec>("cellGeometryTest") {
    group = "verification"
    description = "Runs the cell-grid coordinate and door-wall arithmetic regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.CellGeometryTest"
}

tasks.register<JavaExec>("roomShellTest") {
    group = "verification"
    description = "Runs the pure-Java room shell coordinate regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.RoomShellTest"
}

tasks.register<JavaExec>("roomFurnitureTest") {
    group = "verification"
    description = "Runs the pure-Java room furniture coordinate regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.RoomFurnitureTest"
}

tasks.register<JavaExec>("dungeonShellProtectionTest") {
    group = "verification"
    description = "Runs the pure-Java M31 dungeon-cell shell protection regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DungeonShellProtectionTest"
}

tasks.register<JavaExec>("lobbyBrowserTest") {
    group = "verification"
    description = "Runs the pure-Java lobby directory regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.LobbyBrowserTest"
}

tasks.register<JavaExec>("lodestoneMenuTest") {
    group = "verification"
    description = "Runs the pure-Java lodestone menu construction regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.LodestoneMenuTest"
}

tasks.register<JavaExec>("shellPaletteTest") {
    group = "verification"
    description = "Runs the pure-Java M24 shell palette registry regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.ShellPaletteTest"
}

for ((taskName, testClass) in mapOf(
    "dungeonThemeMetaTest" to "DungeonThemeMetaTest",
    "keystoneOfferTest" to "KeystoneOfferTest",
    "adventureGraphTest" to "AdventureGraphTest",
    "dungeonLogTest" to "DungeonLogTest",
    "taskTrackerTest" to "TaskTrackerTest",
    "rerollMathTest" to "RerollMathTest",
    "gambleMathTest" to "GambleMathTest",
    "powerEquipMathTest" to "PowerEquipMathTest",
    "pocket2Test" to "Pocket2Test",
    "trialContentConfigIdTest" to "TrialContentConfigIdTest",
    "connectorTest" to "ConnectorTest",
    "bountyTrackerTest" to "BountyTrackerTest",
    "cubeStationTest" to "CubeStationTest",
    "roomStoreTest" to "RoomStoreTest",
    "payoutTest" to "PayoutTest",
    // Situations round, registered here by M46B so no other milestone in the
    // round has to open this file. Each class is filled in by its own
    // milestone: M46, M49, M47, M48, M54 and M45 respectively.
    "inventorySwapTest" to "InventorySwapTest",
    "bagTableTest" to "BagTableTest",
    "bagSelectionTest" to "BagSelectionTest",
    "resetCampaignTest" to "ResetCampaignTest",
    "graphSolvabilityTest" to "GraphSolvabilityTest",
    "omenMathTest" to "OmenMathTest",
    // Audit wave 2a: the omen bar's titles, fill and completion verdict.
    "omenBarTextTest" to "OmenBarTextTest",
    "floorShapeTest" to "FloorShapeTest",
    "situationTagsTest" to "SituationTagsTest",
    "dungeonToolsTest" to "DungeonToolsTest",
    "situationSupplyTest" to "SituationSupplyTest",
    "supplySeparationTest" to "SupplySeparationTest",
    // M68: namespaced content identity, legacy resolution, snapshot validation.
    "contentSnapshotTest" to "ContentSnapshotTest",
    // M72: pack validation and release-safe author export (PackValidator).
    "packValidationTest" to "PackValidatorTest",
    // M72: verifies the jar: filesystem walk used by PackValidator.copyResourceTree
    // against a packaged release jar (closes DISCOVERIES item 33).
    "jarFileSystemWalkTest" to "JarFileSystemWalkTest",
    // M75: run memento title/lore/codec/readback regression.
    "runMementoTest" to "RunMementoTest",
    // M78: Endless Mine ruleset (pure policy helpers).
    "endlessMineRulesTest" to "EndlessMineRulesTest",
    // Audit wave 2b: config round trip, zone rules, per-floor banking.
    "configSaveTest" to "ConfigSaveTest",
    "zoneRulesTest" to "ZoneRulesTest",
    "intervalBankingTest" to "IntervalBankingTest"
)) {
    tasks.register<JavaExec>(taskName) {
        group = "verification"
        classpath = sourceSets["test"].runtimeClasspath
        mainClass = "pocketdungeons.$testClass"
    }
}

tasks.test {
    dependsOn("dungeonThemeMetaTest")
    dependsOn("keystoneOfferTest")
    dependsOn("adventureGraphTest")
    dependsOn("dungeonLogTest")
    dependsOn("taskTrackerTest")
    dependsOn("rerollMathTest")
    dependsOn("gambleMathTest")
    dependsOn("powerEquipMathTest")
    dependsOn("pocket2Test")
    dependsOn("trialContentConfigIdTest")
    dependsOn("connectorTest")
    dependsOn("bountyTrackerTest")
    dependsOn("cubeStationTest")
    dependsOn("roomStoreTest")
    dependsOn("payoutTest")
    dependsOn("doorMaskTest")
    dependsOn("planSelectorTest")
    dependsOn("difficultyProfileTest")
    dependsOn("keystoneMathTest")
    dependsOn("affixMathTest")
    dependsOn("dungeonRoomMetaTest")
    dependsOn("cellGeometryTest")
    dependsOn("roomShellTest")
    dependsOn("roomFurnitureTest")
    dependsOn("dungeonShellProtectionTest")
    dependsOn("lobbyBrowserTest")
    dependsOn("lodestoneMenuTest")
    dependsOn("shellPaletteTest")
    dependsOn("pipelineProof")
    dependsOn("layoutGraphTest")
    dependsOn("dungeonIntegrationTest")
    // Situations round. These fail until their milestones land their classes.
    dependsOn("inventorySwapTest")
    dependsOn("bagTableTest")
    dependsOn("bagSelectionTest")
    dependsOn("resetCampaignTest")
    dependsOn("graphSolvabilityTest")
    dependsOn("omenMathTest")
    dependsOn("omenBarTextTest")
    dependsOn("floorShapeTest")
    dependsOn("situationTagsTest")
    dependsOn("dungeonToolsTest")
    dependsOn("situationSupplyTest")
    dependsOn("supplySeparationTest")
    dependsOn("contentSnapshotTest")
    dependsOn("packValidationTest")
    dependsOn("jarFileSystemWalkTest")
    dependsOn("runMementoTest")
    dependsOn("endlessMineRulesTest")
    dependsOn("configSaveTest")
    dependsOn("zoneRulesTest")
    dependsOn("intervalBankingTest")
    failOnNoDiscoveredTests = false
}

tasks.processResources {
    inputs.property("version", project.version)
    filesMatching("fabric.mod.json") {
        expand("version" to project.version)
    }
}

val distDir = rootProject.projectDir.parentFile.resolve("dist")

tasks.register<Copy>("dist") {
    // 26.2 ships unobfuscated, so Loom doesn't register a remapJar task (there's
    // nothing to remap) -- plain `jar` is already the deployable artifact.
    dependsOn("jar")
    from(layout.buildDirectory.dir("libs"))
    into(distDir)
    exclude("*-sources.jar")
}

tasks.named("build") {
    finalizedBy("dist")
    // M72: a build that does not pass pack validation is not a release.
    dependsOn("packValidationTest")
}

tasks.register<JavaExec>("pipelineProof") {
    group = "verification"
    description = "Proves the M3 planner pipeline against a synthetic full room library"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.PipelineProofTest"
}

// Web room editor (tools/room-editor): headless room pack validation. The
// harness lives with the editor, outside src/, and is compiled here against
// the main source set so it can call the mod's own package-private room
// loaders (DungeonRoomMeta.fromJson, RoomManifest.buildEntry). No server is
// booted: the game's registries come from Bootstrap, as in the other headless
// tests. Validate another folder with -ProomsDir=<resources or data/ns path>.
val roomValidatorClasses = layout.buildDirectory.dir("roomValidator/classes")
val compileRoomValidator = tasks.register<JavaCompile>("compileRoomValidator") {
    source = fileTree("tools/room-editor/java") { include("**/*.java") }
    classpath = sourceSets["main"].output + sourceSets["main"].compileClasspath
    destinationDirectory = roomValidatorClasses
}
tasks.register<JavaExec>("validateRooms") {
    group = "verification"
    description = "Runs the mod's own room load checks headlessly over a resources folder (room editor)"
    dependsOn(compileRoomValidator)
    classpath = files(roomValidatorClasses) + sourceSets["main"].runtimeClasspath
    mainClass = "pocketdungeons.RoomPackValidatorMain"
    args(project.findProperty("roomsDir")?.toString() ?: file("src/main/resources").path)
}
