plugins {
    id("net.fabricmc.fabric-loom") version "1.17-SNAPSHOT"
    `java-library`
}

version = "${property("mod_version")}"
group = "${property("maven_group")}"

base {
    archivesName = "MrPinoys_Pocket_Dungeons"
}

repositories {
    mavenLocal()
    maven("https://maven.nucleoid.xyz/") { name = "Nucleoid" }
}

dependencies {
    minecraft("com.mojang:minecraft:${property("minecraft_version")}")
    // No mappings: Minecraft ships unobfuscated since 26.1.
    implementation("net.fabricmc:fabric-loader:${property("loader_version")}")
    implementation("net.fabricmc.fabric-api:fabric-api:${property("fabric_api_version")}")

    // Server-side GUIs. Vanilla clients see an ordinary chest window.
    // Plain implementation rather than modImplementation: 26.x ships unobfuscated, so
    // the remapping modImplementation performs is a no-op here, and its Kotlin DSL
    // accessor is not generated by Loom in this setup.
    implementation("eu.pb4:sgui:2.1.0+26.2")
    include("eu.pb4:sgui:2.1.0+26.2")
}

// M46B: the gametest harness. Loom's own fabric-api integration creates the
// `gametest` source set, a `gameTest` run configuration that inherits `server`
// and sets the `fabric-api.gametest` system property, and the `runGameTest`
// task. Client gametests are off: this mod is server-side only and must never
// pull client classes onto a source set.
//
// The gametest source set carries its own `fabric.mod.json` (mod id
// `pocketdungeons-gametest`), so the `fabric-gametest` entrypoint is declared
// there and nothing test-related enters the shipped jar. `modId` below names
// the Loom classpath group only; it is read from that same file.
fabricApi.configureTests {
    createSourceSet = true
    modId = "pocketdungeons-gametest"
    enableGameTests = true
    enableClientGameTests = false
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

tasks.register<JavaExec>("doorMaskTest") {
    group = "verification"
    description = "Runs the pure-Java DoorMask regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DoorMaskTest"
}

tasks.register<JavaExec>("planSelectorTest") {
    group = "verification"
    description = "Runs the pure-Java RoomSelector/PlanRenderer regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.PlanSelectorTest"
}

tasks.register<JavaExec>("difficultyProfileTest") {
    group = "verification"
    description = "Runs the pure-Java DifficultyProfile regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DifficultyProfileTest"
}

tasks.register<JavaExec>("layoutGraphTest") {
    group = "verification"
    description = "Runs LayoutGraphGenerator's own shape/role/span verification sweep"
    // M40: the harness moved out of production source into the test source
    // set (LayoutGraphGeneratorHarness), so this points at test now, not main.
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.LayoutGraphGeneratorHarness"
}

tasks.register<JavaExec>("payoutMathTest") {
    group = "verification"
    description = "Runs the pure-Java streak and payout arithmetic regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.PayoutMathTest"
}

tasks.register<JavaExec>("dungeonRoomMetaTest") {
    group = "verification"
    description = "Runs the pure-Java DungeonRoomMeta parser regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DungeonRoomMetaTest"
}

tasks.register<JavaExec>("keystoneMathTest") {
    group = "verification"
    description = "Runs the pure-Java keystone level, depletion and timer regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.KeystoneMathTest"
}

tasks.register<JavaExec>("affixMathTest") {
    group = "verification"
    description = "Runs the pure-Java affix set, threshold, seeding and naming regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.AffixMathTest"
}

tasks.register<JavaExec>("cellGeometryTest") {
    group = "verification"
    description = "Runs the cell-grid coordinate and door-wall arithmetic regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.CellGeometryTest"
}

tasks.register<JavaExec>("roomShellTest") {
    group = "verification"
    description = "Runs the pure-Java room shell coordinate regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.RoomShellTest"
}

tasks.register<JavaExec>("roomFurnitureTest") {
    group = "verification"
    description = "Runs the pure-Java room furniture coordinate regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.RoomFurnitureTest"
}

tasks.register<JavaExec>("dungeonShellProtectionTest") {
    group = "verification"
    description = "Runs the pure-Java M31 dungeon-cell shell protection regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.DungeonShellProtectionTest"
}

tasks.register<JavaExec>("lobbyBrowserTest") {
    group = "verification"
    description = "Runs the pure-Java lobby directory regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.LobbyBrowserTest"
}

tasks.register<JavaExec>("lodestoneMenuTest") {
    group = "verification"
    description = "Runs the pure-Java lodestone menu construction regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.LodestoneMenuTest"
}

tasks.register<JavaExec>("shellPaletteTest") {
    group = "verification"
    description = "Runs the pure-Java M24 shell palette registry regression test"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.ShellPaletteTest"
}

for ((taskName, testClass) in mapOf(
    "dungeonThemeMetaTest" to "DungeonThemeMetaTest",
    "keystoneOfferTest" to "KeystoneOfferTest",
    "adventureGraphTest" to "AdventureGraphTest",
    "dungeonLogTest" to "DungeonLogTest",
    "taskTrackerTest" to "TaskTrackerTest",
    "rerollMathTest" to "RerollMathTest",
    "gambleMathTest" to "GambleMathTest",
    "powerEquipMathTest" to "PowerEquipMathTest",
    "pocket2Test" to "Pocket2Test",
    "trialContentConfigIdTest" to "TrialContentConfigIdTest",
    "connectorTest" to "ConnectorTest",
    "bountyTrackerTest" to "BountyTrackerTest",
    "cubeStationTest" to "CubeStationTest",
    "roomStoreTest" to "RoomStoreTest",
    "payoutTest" to "PayoutTest",
    // Situations round, registered here by M46B so no other milestone in the
    // round has to open this file. Each class is filled in by its own
    // milestone: M46, M49, M47, M48, M54 and M45 respectively.
    "inventorySwapTest" to "InventorySwapTest",
    "bagTableTest" to "BagTableTest",
    "bagSelectionTest" to "BagSelectionTest",
    "resetCampaignTest" to "ResetCampaignTest",
    "graphSolvabilityTest" to "GraphSolvabilityTest",
    "omenMathTest" to "OmenMathTest",
    "floorShapeTest" to "FloorShapeTest",
    "situationTagsTest" to "SituationTagsTest",
    "dungeonToolsTest" to "DungeonToolsTest"
)) {
    tasks.register<JavaExec>(taskName) {
        group = "verification"
        classpath = sourceSets["test"].runtimeClasspath
        mainClass = "pocketdungeons.$testClass"
    }
}

tasks.test {
    dependsOn("dungeonThemeMetaTest")
    dependsOn("keystoneOfferTest")
    dependsOn("adventureGraphTest")
    dependsOn("dungeonLogTest")
    dependsOn("taskTrackerTest")
    dependsOn("rerollMathTest")
    dependsOn("gambleMathTest")
    dependsOn("powerEquipMathTest")
    dependsOn("pocket2Test")
    dependsOn("trialContentConfigIdTest")
    dependsOn("connectorTest")
    dependsOn("bountyTrackerTest")
    dependsOn("cubeStationTest")
    dependsOn("roomStoreTest")
    dependsOn("payoutTest")
    dependsOn("doorMaskTest")
    dependsOn("planSelectorTest")
    dependsOn("difficultyProfileTest")
    dependsOn("payoutMathTest")
    dependsOn("keystoneMathTest")
    dependsOn("affixMathTest")
    dependsOn("dungeonRoomMetaTest")
    dependsOn("cellGeometryTest")
    dependsOn("roomShellTest")
    dependsOn("roomFurnitureTest")
    dependsOn("dungeonShellProtectionTest")
    dependsOn("lobbyBrowserTest")
    dependsOn("lodestoneMenuTest")
    dependsOn("shellPaletteTest")
    dependsOn("pipelineProof")
    dependsOn("layoutGraphTest")
    // Situations round. These fail until their milestones land their classes.
    dependsOn("inventorySwapTest")
    dependsOn("bagTableTest")
    dependsOn("bagSelectionTest")
    dependsOn("resetCampaignTest")
    dependsOn("graphSolvabilityTest")
    dependsOn("omenMathTest")
    dependsOn("floorShapeTest")
    dependsOn("situationTagsTest")
    dependsOn("dungeonToolsTest")
    failOnNoDiscoveredTests = false
}

tasks.processResources {
    inputs.property("version", project.version)
    filesMatching("fabric.mod.json") {
        expand("version" to project.version)
    }
}

val distDir = rootProject.projectDir.parentFile.resolve("dist")

tasks.register<Copy>("dist") {
    // 26.2 ships unobfuscated, so Loom doesn't register a remapJar task (there's
    // nothing to remap) -- plain `jar` is already the deployable artifact.
    dependsOn("jar")
    from(layout.buildDirectory.dir("libs"))
    into(distDir)
    exclude("*-sources.jar")
}

tasks.named("build") {
    finalizedBy("dist")
}

tasks.register<JavaExec>("pipelineProof") {
    group = "verification"
    description = "Proves the M3 planner pipeline against a synthetic full room library"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "pocketdungeons.PipelineProofTest"
}
