plugins {
    // Version comes from settings.gradle.kts, which reads it from gradle.properties.
    id("net.fabricmc.fabric-loom")
    `java-library`
}

version = "${property("mod_version")}"
group = "${property("maven_group")}"

base {
    archivesName = "cobbleeconomy"
}

dependencies {
    minecraft("com.mojang:minecraft:${property("minecraft_version")}")
    // No mappings dependency. Minecraft ships unobfuscated with parameter names
    // since 26.1, so there is no deobfuscation step and Yarn is deprecated.
    // Mojang's names ARE the names. Ignore any tutorial written against 1.21 or earlier.

    implementation("net.fabricmc:fabric-loader:${property("loader_version")}")
    implementation("net.fabricmc.fabric-api:fabric-api:${property("fabric_api_version")}")

    // The shop GUI. Vanilla clients see an ordinary chest window. Plain
    // implementation rather than modImplementation: 26.x ships unobfuscated, so the
    // remapping modImplementation performs is a no-op here, and its Kotlin DSL
    // accessor is not generated by Loom in this setup -- same reasoning as ballot
    // and quizengine's sgui dependency.
    implementation("eu.pb4:sgui:2.1.0+26.2")
    include("eu.pb4:sgui:2.1.0+26.2")

    // The economy, shaded into the jar. Server owners drop in one file.
    implementation(project(":core"))
    include(project(":core"))

    // Compile-only: wondrous is a soft dependency (see fabric.mod.json "suggests").
    // Absent at runtime is fine -- WondrousShop degrades to skipping wondrous:
    // listings at shop-load. Plain compileOnly, not modCompileOnly: 26.x ships
    // unobfuscated, so the remapping mod* variants perform is a no-op here, and Loom
    // does not generate that Kotlin DSL accessor in this setup.
    compileOnly("wondrous:wondrous-api:0.1.0")
}

repositories {
    mavenLocal()
    maven("https://maven.nucleoid.xyz/") { name = "Nucleoid" }
}

loom {
    // No client source set: this mod is server-side only.
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

tasks.processResources {
    inputs.property("version", project.version)
    filesMatching("fabric.mod.json") {
        expand("version" to project.version)
    }
}

val distDir = rootProject.projectDir.parentFile.resolve("dist")

tasks.register<Copy>("dist") {
    dependsOn("jar")
    from(layout.buildDirectory.dir("libs"))
    into(distDir)
    exclude("*-sources.jar")
}

tasks.named("build") {
    finalizedBy("dist")
}

